### ISSUE TITLE
[HW] <Abhinai Alavelli>

### ISSUE THREAD

**Issue by abhinai302** [datastaxdevs/workshop-introduction-to-nosql#362]
**Name:** Abhinai Alavelli
**Email:** abhinai302@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/abhinai-alavelli-01ba7220/

Attach the homework screenshots below:
-----------------------------------------

![Cassandra Scenario](https://user-images.githubusercontent.com/79159314/127546261-c1fbab84-1ad9-4d2b-84a5-cedab01945c8.PNG)
![Step-4](https://user-images.githubusercontent.com/79159314/127546296-c8f8d906-b608-40a9-94c6-cb8cca838c8c.PNG)
![Step-4 COL](https://user-images.githubusercontent.com/79159314/127546425-b19f4ce1-132a-4b41-9380-b9a2f15d5226.PNG)

**Comment by hemidactylus** [comment]
Hi, Abhinai!
Well done: you completed the try-it-out scenario!
But it seems the "step 4" of the repo's README (GraphQL for the key-value store) is not completed yet.
It seems you entered the mutation in the CQL Console, while it was meant to be run in the GraphQL playground - and then you would go to the CQL Console to just SELECT the data and check that the data update done in GraphQL is indeed persisted to database.
Please go through the key-value step in the README (step 4) once more and submit a screenshot of the correctly completed task, so that we can then issue you the badge!
See you soon and keep up the good work!
