### ISSUE TITLE
[HW] <Deepak Agarwal>

### ISSUE THREAD

**Issue by deepak934** [datastaxdevs/workshop-introduction-to-nosql#95]
**Name:** <Deepak Agarwal>
**Email:** <deepak934@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/deepak-agarwal-73701951>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
-- images removed by team --
![Home_work4](https://user-images.githubusercontent.com/85251206/120537458-f5568980-c402-11eb-85d6-07750d387ecf.PNG)
![Practice_quiz_completion](https://user-images.githubusercontent.com/85251206/120537459-f5ef2000-c402-11eb-9bb1-291f8cf80220.PNG)

**Comment by deepak934** [comment]
Hi Team,

Can you please review my homework and approve it.

Let me know if there is any steps if i have missed while uploading it.

**Comment by SonicDMG** [comment]
Hi Deepak, looks good. Thank your for your submission. Here's your badge -> https://api.badgr.io/public/assertions/hNn7liayT_KZL5ZmHOzCgg?identity__email=deepak934%40gmail.com. I also removed some images because they included your Astra key. I would delete your Astra token from the Astra UI to be safe.
